version: '3.4'

services:
  eshopwebmvc:
    image: arturcreg.azurecr.io/eshopwebmvc:v1
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
    ports:
      - 80:80
  eshoppublicapi:
    image: arturcreg.azurecr.io/eshoppublicapi:v1
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

